# Update dependencies

version: 2
updates:
# Update the git submodules
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "auto"
  labels:
  - "dependencies"
  - "merge"
  - "enhancement"
  target-branch: "main"
  
