[build]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_THEME         = "toha"
HUGO_VERSION       = "0.149.0"
NODE_VERSION       = "v22.18.0"
NPM_VERSION        = "11.5.2"

[context.split1]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
  HUGO_THEME         = "toha"
  HUGO_VERSION       = "0.149.0"
  NODE_VERSION       = "v22.18.0"
  NPM_VERSION        = "11.5.2"

[context.deploy-preview]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
    HUGO_THEME         = "toha"
    HUGO_VERSION       = "0.149.0"
    NODE_VERSION       = "v22.18.0"
    NPM_VERSION        = "11.5.2"

[context.branch-deploy]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

  [context.branch-deploy.environment]
    HUGO_THEME         = "toha"
    HUGO_VERSION       = "0.149.0"
    NODE_VERSION       = "v22.18.0"
    NPM_VERSION        = "11.5.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
