backend:
  name: git-gateway
  branch: development # Branch to update (optional; defaults to master)
media_folder: ""
public_folder: ""
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    path: '{{year}}-{{month}}-{{day}}-{{slug}}/index'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', default: '', date_format: 'YYYY.DD.MM', time_format: 'HH:mm', format: 'LLL' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ["post"] }
      - { label: 'Featured Image', name: 'hero', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
